from PyQt5 import QtCore, QtGui, QtWidgets

def change_ui4I(instance, MainWindow, date):
    if instance.type_of_window != 4:
        instance.centralwidget.deleteLater()
        instance.type_of_window = 4
        instance.chosen_date =date
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1125, 603)
        instance.centralwidget = QtWidgets.QWidget(MainWindow)
        instance.centralwidget.setObjectName("centralwidget")
        instance.pushButton = QtWidgets.QPushButton(instance.centralwidget)
        instance.pushButton.setGeometry(QtCore.QRect(30, 30, 61, 23))
        instance.pushButton.setCheckable(False)
        instance.pushButton.setObjectName("pushButton")
        instance.pushButton.clicked.connect(lambda: instance.change_ui2(MainWindow))

        instance.label = QtWidgets.QLabel(instance.centralwidget)
        instance.label.setGeometry(QtCore.QRect(300, 100, 471, 31))
        instance.label.setAutoFillBackground(True)
        instance.label.setFrameShape(QtWidgets.QFrame.WinPanel)
        instance.label.setObjectName("label")

        instance.label_2 = QtWidgets.QLabel(instance.centralwidget)
        instance.label_2.setGeometry(QtCore.QRect(300, 150, 471, 31))
        instance.label_2.setAutoFillBackground(True)
        instance.label_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        instance.label_2.setObjectName("label_2")

        instance.label_3 = QtWidgets.QLabel(instance.centralwidget)
        instance.label_3.setGeometry(QtCore.QRect(300, 200, 471, 31))
        instance.label_3.setAutoFillBackground(True)
        instance.label_3.setFrameShape(QtWidgets.QFrame.WinPanel)
        instance.label_3.setObjectName("label_3")
        instance.label_4 = QtWidgets.QLabel(instance.centralwidget)
        instance.label_4.setGeometry(QtCore.QRect(300, 250, 471, 31))
        instance.label_4.setAutoFillBackground(True)
        instance.label_4.setFrameShape(QtWidgets.QFrame.WinPanel)
        instance.label_4.setObjectName("label_4")
        instance.label_5 = QtWidgets.QLabel(instance.centralwidget)
        instance.label_5.setGeometry(QtCore.QRect(190, 120, 91, 31))
        instance.label_5.setAutoFillBackground(True)
        instance.label_5.setFrameShape(QtWidgets.QFrame.WinPanel)
        instance.label_5.setObjectName("label_5")
        instance.label_6 = QtWidgets.QLabel(instance.centralwidget)
        instance.label_6.setGeometry(QtCore.QRect(190, 220, 91, 31))
        instance.label_6.setAutoFillBackground(True)
        instance.label_6.setFrameShape(QtWidgets.QFrame.WinPanel)
        instance.label_6.setObjectName("label_6")
        instance.pushButton_2 = QtWidgets.QPushButton(instance.centralwidget)
        instance.pushButton_2.setGeometry(QtCore.QRect(820, 450, 61, 23))
        instance.pushButton_2.setCheckable(False)
        instance.pushButton_2.setObjectName("pushButton_2")
        instance.pushButton_3 = QtWidgets.QPushButton(instance.centralwidget)
        instance.pushButton_3.setGeometry(QtCore.QRect(820, 490, 61, 23))
        instance.pushButton_3.setCheckable(False)
        instance.pushButton_3.setObjectName("pushButton_3")
        instance.label_7 = QtWidgets.QLabel(instance.centralwidget)
        instance.label_7.setGeometry(QtCore.QRect(300, 350, 471, 31))
        instance.label_7.setAutoFillBackground(True)
        instance.label_7.setFrameShape(QtWidgets.QFrame.WinPanel)
        instance.label_7.setObjectName("label_7")
        instance.label_8 = QtWidgets.QLabel(instance.centralwidget)
        instance.label_8.setGeometry(QtCore.QRect(300, 300, 471, 31))
        instance.label_8.setAutoFillBackground(True)
        instance.label_8.setFrameShape(QtWidgets.QFrame.WinPanel)
        instance.label_8.setObjectName("label_8")
        instance.label_9 = QtWidgets.QLabel(instance.centralwidget)
        instance.label_9.setGeometry(QtCore.QRect(190, 320, 91, 31))
        instance.label_9.setAutoFillBackground(True)
        instance.label_9.setFrameShape(QtWidgets.QFrame.WinPanel)
        instance.label_9.setObjectName("label_9")
        instance.label_10 = QtWidgets.QLabel(instance.centralwidget)
        instance.label_10.setGeometry(QtCore.QRect(300, 450, 471, 31))
        instance.label_10.setAutoFillBackground(True)
        instance.label_10.setFrameShape(QtWidgets.QFrame.WinPanel)
        instance.label_10.setObjectName("label_10")
        instance.label_11 = QtWidgets.QLabel(instance.centralwidget)
        instance.label_11.setGeometry(QtCore.QRect(300, 400, 471, 31))
        instance.label_11.setAutoFillBackground(True)
        instance.label_11.setFrameShape(QtWidgets.QFrame.WinPanel)
        instance.label_11.setObjectName("label_11")
        instance.label_12 = QtWidgets.QLabel(instance.centralwidget)
        instance.label_12.setGeometry(QtCore.QRect(190, 420, 91, 31))
        instance.label_12.setAutoFillBackground(True)
        instance.label_12.setFrameShape(QtWidgets.QFrame.WinPanel)
        instance.label_12.setObjectName("label_12")

        #instance.pushButton_4 = QtWidgets.QPushButton(instance.centralwidget)
        #instance.pushButton_4.setGeometry(QtCore.QRect(780, 130, 31, 23))
        #instance.pushButton_4.setCheckable(False)
        #instance.pushButton_4.setObjectName("pushButton_4")

        #instance.pushButton_5 = QtWidgets.QPushButton(instance.centralwidget)
        #instance.pushButton_5.setGeometry(QtCore.QRect(780, 230, 31, 23))
        #instance.pushButton_5.setCheckable(False)
        #instance.pushButton_5.setObjectName("pushButton_5")
        #instance.pushButton_6 = QtWidgets.QPushButton(instance.centralwidget)
        #instance.pushButton_6.setGeometry(QtCore.QRect(780, 330, 31, 23))
        #instance.pushButton_6.setCheckable(False)
        #instance.pushButton_6.setObjectName("pushButton_6")
        #instance.pushButton_7 = QtWidgets.QPushButton(instance.centralwidget)
        #instance.pushButton_7.setGeometry(QtCore.QRect(780, 430, 31, 23))
        #instance.pushButton_7.setCheckable(False)
        #instance.pushButton_7.setObjectName("pushButton_7")
        instance.lineEdit = QtWidgets.QLineEdit(instance.centralwidget)
        instance.lineEdit.setGeometry(QtCore.QRect(890, 490, 171, 20))
        instance.lineEdit.setObjectName("lineEdit")

        MainWindow.setCentralWidget(instance.centralwidget)
        instance.retranslateUi(MainWindow)
