import random

class Country:
    def __init__(self):
        self.state =["Česká republika",
                        "Spojené státy americké",
                        "Austrálie",
                        "Kanada",
                        "Brazílie",
                        "Japonsko",
                        "Německo",
                        "Itálie",
                        "Spojené království",
                        "Francie",
                        "Rusko",
                        "Čína",
                        "Indie",
                        "Mexiko",
                        "Španělsko",
                        "Jižní Korea",
                        "Turecko",
                        "Indonésie",
                        "Saúdská Arábie",
                        "Argentina",
                        "Jižní Afrika",
                        "Nizozemsko",
                        "Belgie",
                        "Řecko",
                        "Portugalsko",
                        "Švédsko",
                        "Norsko",
                        "Polsko",
                        "Izrael",
                        "Thajsko",
                        "Ukrajina",
                        "Írán",
                        "Pákistán",
                        "Malajsie",
                        "Chile",
                        "Nigérie",
                        "Egypt",
                        "Filipíny",
                        "Bangladéš",
                        "Vietnam",
                        "Etiopie",
                        "Maroko",
                        "Kolumbie",
                        "Irsko",
                        "Peru",
                        "Nový Zéland",
                        "Dánsko",
                        "Singapur",
                        "Maďarsko",
                        "Rakousko",
                        "Venezuela",
                        "Rumunsko",
                        "Čile",
                        "Slovensko",
                        "Bulharsko",
                        "Finsko",
                        "Chorvatsko",
                        "Kostarika",
                        "Libanon",
                        "Katar",
                        "Uruguay",
                        "Panama",
                        "Gruzie",
                        "Litva",
                        "Egypt",
                        "Kambodža",
                        "Slovinsko",
                        "Lotyšsko",
                        "Bahrajn",
                        "Estonsko",
                        "Paraguay",
                     "Albánie",
                     "Alžírsko",
                     "Andorra",
                     "Angola",
                     "Bahamy",
                     "Bahrajn",
                     "Bangladéš",
                     "Barbados",
                     "Bělorusko",
                     "Belgie",
                     "Belize",
                     "Benin",
                     "Bhútán",
                     "Bolívie",
                     "Bosna a Hercegovina",
                     "Botswana",
                     "Brazílie",
                     "Brunej",
                     "Bulharsko",
                     "Burkina Faso",
                     "Burundi",
                     "Čad",
                     "Černá Hora",
                     "Česká republika",
                     "Čína",
                     "Dánsko",
                     "Dominika",
                     "Dominikánská republika",
                     "Džibutsko",
                     "Egypt",
                     "Ekvádor",
                     "Eritrea",
                     "Estonsko",
                     "Eswatini",
                     "Etiopie",
                     "Fidži",
                     "Filipíny",
                     "Finsko",
                     "Francie",
                     "Gabon",
                     "Gambie",
                     "Ghana",
                     "Grenada",
                     "Gruzie",
                     "Guatemala",
                     "Guinea",
                     "Guinea-Bissau",
                     "Guyana",
                     "Haiti",
                     "Honduras"
                     ]

    def get_random_state(self):
        print(random.choice(self.state))