import random

class Fun_factorior:
    def __init__(self):
        self.facts = ["Koala má otisky na nose podobné lidským otiskům prstů.",
                      "Včely mohou cítit únavu.","Mravenci se nepotřebují vyspat.",
                      "Krokodýli nemohou vyčnívat jazykem.",
                      "Sloni jsou jediní savci, kteří nemají skutečný kloub v koleni.",
                      "Žraloci jsou starší než dinosauři.",
                      "Růžové delfíny existují.",
                      "Vážky mají oči tvořené třemi tisíci malými čočkami.",
                      "Medvídci se mohou stát leváti.",
                      "Kočky mají více kostí než lidé.",
                      "Průměrný mravenečník může zvednout 50krát svou vlastní hmotnost.",
                      "Vydry mají oblíbené oblíbené kameny, které nosí s sebou.",
                      "Hlodavci neustále rostou.","Pavouci nespí.",
                      "Platypus má vajíčka, ale je savcem.",
                      "Moucha trvá asi méně než jedna sekunda, aby čichala něco chutného.",
                      "Hadi nemají uši.",
                      "Kaméleon může pohltit něco, co váží dvakrát tolik jako on sám.",
                      "Hroši mohou být agresivní.","Kočky mají 32 svalů v každém uchu.",
                      "Klokani jsou leváti.","Velryby mají srdce tak velké jako malé auto.",
                      "Některé kočky jsou alergické na lidi.",
                      "Kohouti mohou být levostranní nebo pravostranní.",
                      "Jedna lžíce medu je životní prací 12 včel.",
                      "Brouci mohou skákat až 100krát svou délku.",
                      "Kočky mají vynikající paměť.",
                      "Lvi mohou spát až 20 hodin denně.",
                      "Žáby mohou polykat své jídlo tak, že tlačí své oči dolů do ústní dutiny.",
                      "Mnoho ptáků je leváčů.",
                      "Ostrov Christmas je domovem největších krabů na světě.",
                      "Papoušci mohou opakovat lidskou řeč.",
                      "Ptáci mají hromadění v plících, která je umožňují létat na vysokých výškách.",
                      "Delfíni mají větší mozky než lidé.",
                      "Kočky mohou mít různé barvy očí.",
                      "Kamzíci mají větší rohy než samci.",
                      "Včely komunikují tancem.",
                      "Plazi nemají pocit v chvostu.",
                      "Kůže žraloka je odolnější než beton.",
                      "Vážky mohou létat rychlostí až 58 km/h.",
                      "Hadi mohou spát až několik měsíců bez jídla.",
                      "Veverky mohou chytit krvavé oči.",
                      "Kočky mohou mít čtyři prsty na předních tlapách, ale pouze pět prstů na zadních tlapách.",
                      "Ptáci mají lepší zrak než lidé.",
                      "Želvy mají žádné zuby.",
                      "Bulbuly mají nejdelší křídla ze všech ptáků.",
                      "Pavouci mohou zpívat.",
                      "Klokaní klokan může zvednout více než dvakrát svou hmotnost.",
                      "Krokodýli mohou vychutnat sluneční svit na zubech.",
                      "Chameleons nejsou jediné zvíře, které může změnit barvu.",
                      "Vlci se rádi mazlí.",
                      "Kočky se rády otírají o lidi.",
                      "Včely nejsou jediné opylovače.",
                      "Žraloci jsou ohroženi vyhubením.",
                      "Včely tančí, aby sdělily ostatním včelám, kde je nejlepší zdroj nektaru.",
                      "Kamzíci se mohou vyhnout svým predátorům tím, že se předstírají, že spadli ze skály.",
                      "Kočky mohou chodit na špici.",
                      "Vážka může mít až 80 000 očí.",
                      "Sloni mají vynikající paměť.",
                      "Ptáci mohou spát ve vzduchu.",
                      "Želvy mohou dýchat skrz své zadečky.",
                      "Žraloci mohou cítit krev ve vodě až z kilometry dál.",
                      "Mravenci mohou držet svůj dech až 24 hodin.",
                      "Hlodavci mohou zvracet, aby se zbavili predátora.",
                      "Vlaštovky jsou znamením štěstí.",
                      "Kočky mohou být praváci nebo leváci.",
                      "Sova může zatočit hlavou o 270 stupňů.",
                      "Pavouci jí pavouky.",
                      "Vlci mají různé křiky pro různé situace.",
                      "Medvědi se nemohou vrátit na místo, kde byli zraněni.",
                      "Kočky mohou chodit zpětně.",
                      "Včely umí počítat do čtyř.",
                      "Žraloci jsou téměř nemrtví.",
                      "Plazi nemají ani jednu bradavici.",
                      "Klokani nemohou skákat zpět.",
                      "Želvy mají výborný smysl pro rovnováhu.",
                      "Mravenci mohou být leváci nebo praváci.",
                      "Kočky mají jedinečné otisky tlap.",
                      "Pavouci jedí své staré pavučiny.",
                      "Vlci komunikují pomocí vyceněných zubů.",
                      "Hlodavci si pravidelně obrušují zuby na tvrdé předměty.",
                      "Medvědi mohou plavat až 100 km v jednom kuse.",
                      "Klokani mají silné zadní nohy, ale slabé přední nohy.",
                      "Žraloci mají nulovou úmrtnost.",
                      "Včely se mohou rozhodovat většinou.",
                      "Sloni mají nejdelší těhotenství z všech savců.",
                      "Papoušci mají vlastní jméno.",
                      "Ostrov Christmas je známý jako Vánoční ostrov.",
                      "Kohouti mohou utíkat rychlostí až 16 km/h.",
                      "Kočky mají nejrychlejší reakční čas mezi zvířaty.",
                      "Vlci mají velkou variabilitu ve svých hlasových projevech.",
                      "Pavouci používají vibrace k lovení kořisti.",
                      "Veverky mohou zapamatovat tisíce skrýší.",
                      "Kočky mohou mít až 100 různých zvuků.",
                      "Želvy mohou cestovat dlouhé vzdálenosti přes pevninu.",
                      "Ptáci mají lepší čich než lidé.",
                      "Hlodavci mají stálé a rostoucí zuby.",
                      "Medvědi mohou spát až 7 měsíců v zimě.",
                      "Krokodýli mají nejvíce smyslů ze všech plazů.",
                      "Žraloci se narodí s plně vyvinutými zuby.",
                      "Včely mají složité taneční jazyky pro komunikaci.",
                      "Pavouci jsou jedni z nejlepších lovců v říši hmyzu.",
                      "Klokani mají silné ocasní svaly k podpoře skoků.",
                      "Kočky mají nezávislé smysly.",
                      "Hlodavci mají speciální zuby k žvýkání dřeva.",
                      "Medvědi mají výtečný čich na velkou vzdálenost.",
                      "Ptáci mohou spát s jedním okem otevřeným.",
                      "Pavouci mohou být leváci nebo praváci.",
                      "Velryby mohou mít hloubkový zápis v mozku.",
                      "Vlci mají sociální strukturu jako lidé.",
                      "Želvy mohou komunikovat pomocí zvuků.",
                      "Kočky mohou mít ambidextrozní tlapky.",
                      "Včely mohou cítit elektrostatické pole květů.",
                      "Hlodavci mají vysokou rychlost reprodukce.",
                      "Pavouci používají své síťoviny k uložení potravy.",
                      "Žraloci mají vynikající imunitní systém.",
                      "Ptáci mají duté kosti pro lehkost při letu.",
                      "Medvědi mají vysokou inteligenci.",
                      "Klokani mají silné svaly k pohybu pomocí skoků.",
                      "Včely mohou vnímat ultrazvuk.",
                      "Pavouci mohou být extrémně trpěliví při lovu kořisti.",
                      "Vlci mají vynikající smysl pro společenskou hierarchii.",
                      "Želvy mohou mít dlouhověkost až 100 let.",
                      "Kočky mohou spát až 16 hodin denně.",
                      "Ptáci mají tříbarevné vizuální spektrum.",
                      "Hlodavci mají schopnost rychle se rozmnožovat.",
                      "Medvědi mají vysokou tolerance k bolesti.",
                      "Klokani mají silné zadní nohy k rychlému útěku.",
                      "Včely mají složité navigační schopnosti pomocí slunečního světla.",
                      "Pavouci mohou jíst svou starou kůži po svlékání.",
                      "Žraloci mají schopnost regenerovat zuby.",
                      "Ptáci mají schopnost rozpoznat si jednotlivé písně.",
                      "Kočky mají vysoký stupeň flexibility.",
                      "Vlci mají vysokou míru spolupráce při lovu.",
                      "Želvy mají schopnost cítit magnetické pole Země.",
                      "Hlodavci mají vysokou schopnost adaptace na různé prostředí.",
                      "Medvědi mají schopnost se orientovat pomocí slunečního světla.",
                      "Klokani mají silné svaly na skákání a šplhání.",
                      "Včely mají vysokou schopnost komunikace pomocí tance.",
                      "Pavouci mají schopnost cítit vibrace pomocí svých nohou.",
                      "Žraloci mají schopnost cítit elektromagnetické pole kořisti.",
                      "Ptáci mají schopnost udržovat rovnováhu ve vzduchu.",
                      "Kočky mají schopnost využívat své tlapky jako nástroje k lovu kořisti.",
                      "Vlci mají schopnost komunikovat pomocí různých zvuků.",
                      "Želvy mají schopnost cítit dotek pomocí své kůže.",
                      "Hlodavci mají schopnost rozeznat pachy pomocí svého čichu.",
                      "Medvědi mají schopnost cítit pohyb pomocí svých vibračních smyslů.",
                      "Klokani mají schopnost přizpůsobit se různým podmínkám prostředí.",
                      "Včely mají schopnost nalézt nektarpomocí svého čichu.",
                      "Pavouci mají schopnost cítit teplotní změny pomocí svých nohou.",
                      "Žraloci mají schopnost cítit tlak vody pomocí svých smyslů.",
                      "Ptáci mají schopnost cítit pohyb vzduchu pomocí svých křídel.",
                      "Kočky mají schopnost cítit pohyb vody pomocí svých vibračních smyslů.",
                      "Vlci mají schopnost cítit pohyb půdy pomocí svých tlapek.",
                      "Želvy mají schopnost cítit změny teploty pomocí svých čichových smyslů.",
                      "Hlodavci mají schopnost cítit vibrace v půdě pomocí svých nohou.",
                      "Medvědi mají schopnost cítit pachy větru pomocí svého čichu.",
                      "Klokani mají schopnost cítit změny tlaku vzduchu pomocí svých nosních dírků.",
                      "Včely mají schopnost cítit vzdálenost a směr pomocí slunečního světla.",
                      "Pavouci mají schopnost cítit vibrace kořisti pomocí svých nohou.",
                      "Žraloci mají schopnost cítit elektrické pole vody pomocí svých smyslů.",
                      "Ptáci mají schopnost cítit pohyb vzduchu pomocí svých peří.",
                      "Kočky mají schopnost cítit změny tlaku vzduchu pomocí svých uší.",
                      "Vlci mají schopnost cítit změny pohybu vzduchu pomocí svých nozder.",
                      "Želvy mají schopnost cítit změny magnetického pole Země pomocí svých smyslů.",
                      "Hlodavci mají schopnost cítit změny teploty vzduchu pomocí svých nosních dírek.",
                      "Medvědi mají schopnost cítit vibrace vody pomocí svých tlapek.",
                      "Klokani mají schopnost cítit změny tlaku vody pomocí svých tlap.",
                      "Včely mají schopnost cítit elektrický náboj květin pomocí svých smyslů.",
                      "Pavouci mají schopnost cítit změny tlaku vzduchu pomocí svých nohou.",
                      "Žraloci mají schopnost cítit elektrické pole vody pomocí svých nozder.",
                      "Ptáci mají schopnost cítit změny tlaku vzduchu pomocí svých peří.",
                      "Kočky mají schopnost cítit změny pohybu vzduchu pomocí svých vibračních smyslů.",
                      "Vlci mají schopnost cítit změny tlaku vzduchu pomocí svých čichových smyslů.",
                      "Želvy mohou rozpoznat vůni potravy i přes velkou vzdálenost.",
                      "Hlodavci mají schopnost identifikovat potravu pomocí svého čichu.",
                      "Medvědi mají silný čich schopný detekovat potravu na dlouhou vzdálenost.",
                      "Klokani mají vynikající schopnost odhadnout vzdálenost při skoku.",
                      "Včely mohou rozpoznat svůj úl i v hustém roji.",
                      "Pavouci mohou přesně odhadnout velikost své kořisti pomocí dotyku.",
                      "Žraloci mají citlivý čich schopný detekovat krev v koncentraci až jedna část na milion.",
                      "Ptáci mají schopnost rozpoznat jednotlivé jedince svého druhu podle zvuku jejich písní.",
                      "Kočky mají vynikající schopnost lovu díky svému tichému pohybu a ostrému zraku.",
                      "Vlci mají vyvinutou taktiku lovu založenou na spolupráci a vzájemné komunikaci v rámci smečky.",
                      "Želvy mají schopnost najít cestu zpět k místu svého narození pomocí magnetického pole Země.",
                      "Hlodavci mají dobře vyvinutou schopnost hledání"
                      " potravy a skrýš pomocí paměti a orientace v prostoru.",
                      "Medvědi mají vynikající paměť a mohou si zapamatovat polohu potenciálně nebezpečných míst.",
                      "Klokani mají schopnost rychle se přizpůsobit různým podmínkám prostředí a změnám v ekosystému.",
                      "Včely mají složitý systém komunikace založený na tanci a feromonových stopách,"
                      " které jim pomáhají najít zdroje potravy a navigovat kolem úlu.",
                      "Pavouci mají schopnost přizpůsobit svou síťovinu různým podmínkám prostředí a typům kořisti.",
                      "Žraloci mají vynikající smysl pro orientaci a mohou urazit dlouhé vzdálenosti "
                      "při migraci pomocí magnetických polí a geografických orientačních bodů.",
                      "Ptáci mají schopnost navigovat dlouhé vzdálenosti během migrace pomocí slunce, "
                      "hvězd, magnetického pole Země a vizuálních orientačních bodů.",
                      "Kočky mají schopnost adaptovat své lovné strategie podle typu kořisti a prostředí,"
                      " ve kterém se nacházejí.",
                      "Vlci mají vyspělý sociální systém založený na hierarchii a spolupráci,"
                      " což jim umožňuje efektivně lovit i chránit smečku před nebezpečím.",
                      "Želvy mají schopnost detekovat změny teploty prostředí a přizpůsobit svou"
                      " aktivitu podle těchto podmínek.",
                      "Hlodavci mají vynikající schopnost vyhledávat potravu v různých typech prostředí,"
                      " včetně zemědělských oblastí a městských oblastí.",
                      "Medvědi mají vysokou toleranci k chladu a mohou přežívat v"
                      " extrémních podmínkách Arktidy a Antarktidy.",
                      "Klokani mají schopnost přemisťovat se na dlouhé vzdálenosti pomocí skoků a přizpůsobit se"
                      " různým typům terénu.",
                      "Včely mají vynikající schopnost vyhledávat nektar a pyl z květin v okolí "
                      "svého úlu a přenášet tyto zdroje zpět do úlu k vykrmení larv a výživě včelí kolonie.",
                      "Pavouci mají schopnost rychle reagovat na změny v prostředí a upravit "
                      "své chování a lovné strategie podle nových podmínek.",
                      "Žraloci mají vynikající schopnost cítit změny chemického složení vody a "
                      "identifikovat potenciální zdroje potravy v okolí.",
                      "Ptáci mají vysoce vyvinutý smysl pro zvuk a mohou rozpoznat a "
                      "interpretovat různé zvuky ve svém prostředí, včetně písní druhů svého druhu a hlasů predátorů.",
                      "Kočky mají vysokou míru inteligence a schopnost učit se nové triky a "
                      "dovednosti od svých majitelů i samy od sebe.",
                      "Vlci mají vynikající koordinační schopnosti a mohou spolupracovat při složitých úkolech, "
                      "jako je lov kořisti nebo ochrana smečky před vnějšími hrozbami.",
                      "Želvy mají vysokou míru adaptace a mohou přežívat v různých typech prostředí,"
                      " včetně pouští, lesů, bažin a horských oblastí.",
                      "Hlodavci mají schopnost rozpoznat a reagovat na různé druhy potravy a "
                      "zdroje vody v jejich okolí pomocí svého čichu a chuti.",
                      "Medvědi mají schopnost efektivně vyhledávat potravu v širokém spektru prostředí, "
                      "včetně lesů, hor, bažin a pobřežních oblastí.",
                      "Klokani mají schopnost regulovat svou teplotu těla podle změn okolního prostředí a udržovat"
                      " si konstantní tělesnou teplotu i v extrémních podmínkách.",
                      "Včely mají vynikající schopnost orientace ve vzduchu a mohou navigovat v okolí svého úlu"
                      " pomocí vizuálních orientačních bodů a slunečního světla.",
                      "Pavouci mají schopnost adaptovat své lovné techniky a strategie podle typu kořisti a prostředí,"
                      " ve kterém loví.",
                      "Žraloci mají vynikající schopnost vyhledávat a identifikovat potenciální "
                      "zdroje potravy ve svém prostředí a rychle reagovat na změny v distribuci kořisti.",
                      "Ptáci mají schopnost detekovat a interpretovat různé typy signálů ve"
                      " svém prostředí a přizpůsobit své chování podle těchto signálů, včetně signálů hrozby, "
                      "signálů kořisti a signálů společenské interakce.",
                      "Kočky mají vysokou míru flexibilitu a mohou se snadno přizpůsobit různým podmínkám prostředí a "
                      "změnám ve svém životním stylu.",
                      "Vlci mají schopnost efektivně komunikovat mezi sebou pomocí různých zvuků, "
                      "pohybů těla a vizuálních signálů,"
                      " což jim umožňuje koordinovat své chování při lovu, ochraně smečky a sociální interakci.",
                      ]

    def get_random_funfact(self):
        print(random.choice(self.facts))