my_list = ["první prvek", "druhý prvek", "třetí prvek",
            "Květiny byly čerstvě zalité.",
            "Kniha byla pohodlně uložená v regálu.",
            "Psa svrbělo ucho.",
            "Měsíc svítil jasně na noční obloze.",
            "Děti sbíraly mušle na pláži.",
            "Telefon ticho ležel na stole.",
            "Vůně kávy se line kuchyní.",
            "Stromy se lehce hýbaly ve větru.",
            "Pták přistál na okenním parapetu.",
            "Zvonky na dveřích zazvonily.",
            "Auto pomalu projíždělo ulicí.",
            "List papíru byl hladký a bílý.",
            "Hodiny tikaly klidně na stěně.",
            "Skořápka ořechu ležela na zemi.",
            "Záclony byly lehce roztažené.",
            "Pes spokojeně spal na podlaze.",
            "Večer jsme pozorovali hvězdy.",
            "Kočka pronásledovala svůj stín.",
            "Dětský smích zněl ze zahrady.",
            "Svítilna na stěně slabě svítila.",
            "Větrák se zastavil a znovu se rozeběhl.",
            "Strom vrhal dlouhý stín.",
            "Vůně čerstvého pečiva se šířila vzduchem.",
            "Psí miska byla plná granulí.",
            "Kočka ležela skládaná na židli.",
            "Ulice byla mokrá po dešti.",
            "V koupelně kapala voda z kohoutku.",
            "Obloha byla plná letících ptáků.",
            "V knize byla založená záložka.",
            "Vlak hučel v dálce.",
            "Stín padal přes stůl.",
            "Písek byl teplý pod nohama.",
            "Psí hračka ležela na trávníku.",
            "Večerní chlad byl příjemný.",
            "Ráno bylo mlhavé a tajemné.",
            "Děti hrály na houpačkách.",
            "Kniha padla na podlahu.",
            "Ptáci čvirkotali na stromě.",
            "Míček odskočil od zdi.",
            "Oko okna bylo otevřené.",
            "Dveře se zavřely s hlasitým práskem.",
            "Kočka spala na vrhu schodů.",
            "Zahrada byla osvětlena měsíčním svitem.",
            "Na pláži bylo ticho.",
            "Pes běhal kolem stromu.",
            "Děti se schovávaly během hry na schovávanou.",
            "Vejce sizzled na pánvi.",
            "Papírový letadlo plachtí vzduchem.",
            "Knihy byly pečlivě uspořádány na polici.",
            "Hvězdy svítily jasně nade dvorem.",
            "Větvička praskla pod váhou sněhu.",
            "Pes hledal svou ztracenou hračku.",
            "Světlo svítilo z okna do tmy.",
            "Dívka malovala obrázek v parku.",
            "Káva byla nalita do šálku.",
            "Listy šuměly ve větru.",
            "Kočka se tulila k teplému radiátoru.",
            "Auto zastavilo u červeného semaforu.",
            "Míč odrazil od stěny.",
            "Klíče byly zapomenuty na stole.",
            "Děti zpívaly píseň.",
            "Telefon byl odložený na nočním stolku.",
            "Knihovník zařazoval knihy do regálu.",
            "Slnko zapadalo za horu.",
            "Voda bublala v potůčku.",
            "Kabát visel na věšáku.",
            "Psi hráli ve sněhu.",
            "Tráva byla pokryta jinovatkou.",
            "Okno bylo zamžené od dechu.",
            "Student psal zkoušku.",
            "Kočka lozila po stromu.",
            "Papír byl složený na polovinu.",
            "Svíčka plápolala na stole.",
            "Veverka jedla oříšek.",
            "Dětské kresby visely na lednici.",
            "Káva vylila z přeplněného hrnku.",
            "Ptáci se krmili na krmítku.",
            "Kniha byla vrácena do knihovny.",
            "Opona se zatáhla a představení začalo.",
            "Hráči stoupli na startovní čáru.",
            "Vlak pískal při odjezdu ze stanice.",
            "Dítě házelo kameny do rybníka.",
            "Psaní na stroji znělo v tiché místnosti.",
            "Džus byl rozlitý na podlaze.",
            "Písmena byla vyryta do dřeva.",
            "Půlnoční hvězdy svítily jasně.",
            "Zvon zvonil na konci školní hodiny.",
            "Měsíc byl plný a jasný.",
            "Oheň praskal v krbu.",
            "Větrovka byla pověšená na háčku.",
            "Ořechy byly rozdrcené pro pečení.",
            "Pes si lehl na své oblíbené místo.",
            "Růže byly postříkány vodou.",
            "Děti čekaly na autobus.",
            "Vítr převrátil květináč.",
            "Zápisky byly pečlivě sepsány.",
            "Rybář seděl u řeky.",
            "Párek v rohlíku byl servírován s hořčicí.",
            "Lístek byl připevněn na nástěnku.",
            "Sova houkala v noci.",
            "Dveře se pomalu otevřely a vstoupil dovnitř.",
            "Koláč ochladil na parapetu.",
            "Slunce svítilo na kapky rosy na trávě.",
            "Děti skákaly do louže.",
            "Káva voněla v celé kuchyni.",
            "Listí bylo zameteno do kouta zahrady.",
            "Pes si vyhrabal díru pod plotem.",
            "Ptáci se shlukovali na drátech vysokého napětí.",
            "Čaj byl příliš horký na to, aby se pil okamžitě.",
            "Měsíc ozařoval klidné jezero.",
            "Dívka skládala papírové lodičky.",
            "Větrovka visela na ramínku ve skříni.",
            "Vajíčka byla uvařená natvrdo.",
            "Kočka předla spokojeně na pohovce.",
            "Motýli tancovali nad květinami.",
            "Otec opravoval zlomené kolo.",
            "Kniha byla pohřbená pod hromadou časopisů.",
            "Pero bylo ztraceno mezi polštáři gauče.",
            "Hodiny odbily půlnoc.",
            "Světla se rozsvítila v celém divadle.",
            "Vejce byla nakrájena na salát.",
            "Pes běžel za vrhaným míčem.",
            "Stromy vrzaly ve větru.",
            "Skořápky ořechů byly roztroušené po zemi.",
            "Klíče byly nalezeny pod gaučem.",
            "Zvuk vody byl uklidňující.",
            "Pes skočil do rybníka.",
            "Pták zpíval na střeše.",
            "Děti postavily sněhuláka na zahradě.",
            "Kočka se snažila chytit svůj odraz v zrcadle.",
            "Děti se smály při sledování filmu.",
            "Papírový drak letěl vysoko na obloze.",
            "Strom padl během bouřky.",
            "Všechny svíčky na dortu byly zhasnuty.",
            "Ráno začalo zpěvem ptáků.",
            "Káva se rozlila na ubrus.",
            "Auto bylo zaparkováno pod stromem.",
            "Větvičky byly rozloženy pro oheň.",
            "Děti sbíraly kamínky na břehu řeky.",
            "V noci svítil měsíc.",
            "Kočka se olizovala ve slunečním svitu.",
            "Psí pelíšek byl umístěn vedle krbu.",
            "Ptáci vybírali semínka z krmítka.",
            "Džíny byly pověšeny k oschnutí.",
            "Růže byly ponořeny ve váze s vodou.",
            "Auto projíždělo loužemi.",
            "Knihy byly rozloženy na stole.",
            "Děti hrály hru na zahradě.",
            "Káva se vařila na sporáku.",
            "Lístky na stromech se měnily na podzimní barvy.",
            "Ořechy byly rozdrceny pro vánoční cukroví.",
            "Hodiny tikaly tichě v prázdné místnosti.",
            "Sova houkala z větve starého dubu.",
            "Rybář seděl ticho u břehu jezera.",
            "Děti skákaly přes švihadlo na hřišti.",
            "Pes spal ve stínu stromu.",
            "Vítr foukal listí po ulici.",
            "Zahrada byla plná zralých rajčat.",
            "Děti stavěly hrad z písku.",
            "V kuchyni voněly čerstvě upečené koláče.",
            "Pták vykukoval z ptačí boudy.",
            "Kočka se plížila za motýlem.",
            "Knihy byly seřazeny podle barvy na polici.",
            "Auto zpomalilo před školou.",
            "Kapky deště bubnovaly na střechu.",
            "Pes pronásledoval svůj stín na trávníku.",
            "Děti malovaly obrázky vodovými barvami.",
            "Strom vrhal dlouhý stín na trávník.",
            "Motýl přistál na květině.",
            "Kočka spala svíjená v křesle.",
            "Světlo lampy zlatě osvětlovalo knihu.",
            "Děti hrály na zahradě schovávanou.",
            "Pes běžel po pláži za míčem.",
            "Růže byly pokropeny rosením.",
            "Vlak pískal, když projížděl městem.",
            "Dívka četla knihu pod stromem.",
            "Káva kapala do konvice.",
            "Ptačí zpěv naplňoval ráno.",
            "Děti krmily kachny u rybníka.",
            "Hvězdy svítily na noční obloze.",
            "Větrovka visela na vchodových dveřích.",
            "Pes spal na svém oblíbeném polštáři.",
            "Rybáři seděli u břehu s pruty.",
            "Dveře se zavřely s hlasitým práskem.",
            "Kočka se vyhřívala na slunci.",
            "Stromy se ohýbaly ve větru.",
            "Děti plavaly v jezeře.",
            "Ptáci sbírali větvičky pro stavbu hnízd.",
            "Pes vyhrabal díru pod plotem.",
            "Večerní chlad přinášel úlevu po horkém dni.",
            "Kniha byla ponechána na lavičce v parku.",
            "Stín se protáhl přes chodník.",
            "Kočka škrábala na svém škrabadle.",
            "Děti se smály a křičely během hry.",
            "Měsíc svítil přes mraky.",
            "Větrovka byla pověšená na háku vedle dveří.",
            "Pták zpíval z koruny stromu.",
            "Kočka miaula u dveří, chtěla jít ven.",
            "Děti sesbíraly všechny hračky do krabice.",
            "Světla ve městě se postupně rozsvěcela s přicházejícím večerem.",
            "Autobusy byly na zastávce plné lidí.",
            "Káva přetejkala z hrnku na stole.",
            "Ptáci začali zpívat s prvními paprsky slunce.",
            "Kočka se mazlila u nohou svého majitele.",
            "Děti sbíraly lístky pro školní projekt.",
            "Ranní mlha pokrývala polní cesty.",
            "Pes vyštěkl, když slyšel zvonek.",
            "Dívka si vázala tkaničky na nových botách.",
            "Večerní film začínal v osm hodin.",
            "Stromy byly pokryty bílou námrazou.",
            "Pes přinesl míč zpět svému majiteli.",
            "Kočka ulovila motýla ve vzduchu.",
            "Děti malovaly obrázky na chodníku křídami.",
            "Větrovka byla zavěšena na ramínku ve skříni.",
            "Káva voněla po celém domě.",
            "Pták zpíval na stromě před domem.",
            "Světla aut osvětlovala silnici ve tmě.",
            "Rybář vylovil rybu z řeky.",
            "Kočka si hrála se stínem na zdi.",
            "Děti se vrhly do bazénu s pláštěnkami.",
            "Dům byl tichý, všichni spali.",
            "Večerní bríza ochladila vzduch.",
            "Děti pustily papírové lodičky na potoku.",
            "Pes sledoval každý pohyb svého majitele.",
            "Kočka skočila na vysokou skříň.",
            "Děti zpívaly písničky u táborového ohně.",
            "Káva se přelila přes okraj hrnku.",
            "Vlak projížděl městem s hlučným houkáním.",
            "Sova seděla na větvi a pozorovala níže.",
            "Děti běžely za svým psem po parku.",
            "Noční nebe bylo jasné a plné hvězd.",
            "Kočka mňoukala, když cítila blížící se oběd.",
            "Ráno se rozednívalo s každou minutou.",
            "Děti skákaly přes provaz na hřišti.",
            "Voda v jezeře byla klidná a tichá.",
            "Hodiny bily půlnoc a dům byl tichý.",
            "Pes spal na své dečce u ohně.",
            "Děti se chystaly na noční příběh.",
            "Kočka sledovala ptáky z okenního parapetu.",
            "Dívka si četla knihu pod starým dubem.",
            "Ranní světlo prosvětlovalo záclony.",
            "Káva kápla na bílou ubrus.",
            "Ptákův zpěv byl prvním zvukem rána.",
            "Děti postavily stan na zahradě.",
            "Vítr hladil listy na stromech.",
            "Děti naslouchaly příběhům své babičky.",
            "Kočka spadla z okenního parapetu, ale dopadla na nohy.",
            "Rybáři seděli na břehu řeky a čekali.",
            "Večerní hvězdy začaly blikat na nebi.",
            "Pes vřeštěl, když viděl pošťáka přicházet k domu.",
            "Autobus zastavil s hlasitým skřípěním brzd.",
            "Růže rozkvetly v plné kráse.",
            "Veverka utekla po stromu nahoru s oříškem.",
            "Kočka seděla a dívala se z okna.",
            "Děti skákaly do bazénu se smíchem.",
            "Noční mlha se snášela nad město.",
            "Pes honil svůj stín na zahradě.",
            "Větrník se otáčel ve větru.",
            "Květiny byly zavlažovány raní rosou.",
            "Pták si budoval hnízdo v keři.",
            "Dívka sbírala pampelišky na louce.",
            "Kámen skákal po hladině rybníka.",
            "Vlak vyjížděl ze stanice.",
            "Sova houkala v noci.",
            "Děti vyhrály fotbalový zápas.",
            "Kočka se hrabala v písku.",
            "Děti sledovaly, jak se chroustáli v zemi.",
            "Záclony byly zatáhnuty a v místnosti bylo ticho.",
            "Rybář chytil velkou rybu.",
            "Hráči se rozcvičovali před zápasem.",
            "Vejce byla pečlivě uskladněna v kartonu.",
            "Auto pomalu projíždělo po kluzké silnici.",
            "Děti rozsvítili táborový oheň.",
            "Kočka spala na světlém slunečním paprsku.",
            "Pes přinesl zpět vrženou hračku.",
            "Listy stromů jemně šelestily.",
            "Dívka napsala dopis svému příteli.",
            "V parku byly vysázeny nové stromy.",
            "Káva voněla při přípravě.",
            "Večer se rozhořely grily.",
            "Děti chytaly ryby na jezeře.",
            "Pes vřeštěl na poštovní schránku.",
            "Zahradník zastřihoval živý plot.",
            "Děti hrály na hřišti.",
            "Kočka pronásledovala motýla.",
            "Oheň v krbu praskal.",
            "Rybáři seděli na břehu a sledovali vodu.",
            "Hvězdy svítily jasně na večerní obloze.",
            "Vítr vanul přes pole.",
            "Děti zpívaly písničky u táboráku.",
            "Káva byla nalita do šálků.",
            "Autobus přijel na zastávku.",
            "Děti si hrály v písku.",
            "Kočka mňoukala u dveří.",
            "Pes běžel k majiteli.",
             ]