import random
from sentence2 import my_list

class SentenceFactory:
    def __init__(self):
        self.sentences = [
            "Ahoj, jak se máš?",
            "Dnes je krásné počasí.",
            "Mám rád, když věci fungují.",
            "Mám rád, když věci fungují.",
            "Ráno se probudil a vyhlédl z okna.",
            "Kočka seděla na střeše a dívala se dolů.",
            "Ulice byly po dešti kluzké.",
            "Auto zaparkovalo přímo před domem.",
            "Slunce pomalu zapadalo za horizont.",
            "Děti hrály fotbal na zahradě.",
            "Pes štěkal na poštovního doručovatele.",
            "Všechno špatné je pro něco dobré.",
            "V kavárně hrála příjemná hudba.",
            "Stůl byl plný knih a časopisů.",
            "Zmrzlina rychle roztála ve slunci.",
            "Ztratil klíče a nemohl se dostat dovnitř.",
            "Telefon zvonil, ale nikdo neodpovídal.",
            "V parku bylo plno lidí.",
            "Pohled z okna byl dechberoucí.",
            "Kniha ležela otevřená na stole.",
            "Autobus přijel přesně na čas.",
            "Džus byl osvěžující a sladký.",
            "Větrník se točil na střeše.",
            "Učitel vysvětloval složitý problém.",
            "Svítilna na stole přestala fungovat.",
            "Děti sbíraly kamínky na pláži.",
            "Všechny květiny ve váze uvadly.",
            "Pes si hrál se svou hračkou.",
            "Obloha byla čistě modrá.",
            "Četl si noviny při snídani.",
            "Telefonní hovor byl krátký a stručný.",
            "Vajíčka na snídani byla akorát.",
            "Na stěně visel nový obraz.",
            "Psala dlouhý dopis svému příteli.",
            "Večer jsme šli na koncert.",
            "Auto bylo po nehodě poničené.",
            "Ráno bylo chladno a mlhavo.",
            "Květináč na parapetu spadl.",
            "Všichni tleskali na konci představení.",
            "Zmrzlina byla příliš tvrdá na to, aby se dala lžící nabrat.",
            "Veverka skákala z větve na větev.",
            "Káva byla silnější, než obvykle.",
            "Pták zpíval na střeše.",
            "Šálek na čaj se rozbil o zem.",
            "Ulice byla po bouřce plná větví.",
            "Věci byly rozhozené po celém pokoji.",
            "Kniha spadla ze stolu.",
            "Větrák se otáčel pomalu.",
            "Děti kreslily křídou na chodníku.",
            "Stůl byl pokrytý papíry.",
            "Večerní film byl zábavný.",
            "Otevřel okno, aby větral.",
            "Sousedé měli hlasitou párty.",
            "Pes spal v koutě pokoje.",
            "Oblaky se hromadily nad městem.",
            "Listí šustilo pod nohama.",
            "Zavřel knihu a postavil ji na polici.",
            "V noci bylo slyšet hřmění.",
            "Auto bylo umyté a čisté.",
            "Ráno se probudil a vyhlédl z okna.",
            "Kočka seděla na střeše a dívala se dolů.",
            "Ulice byly po dešti kluzké.",
            "Auto zaparkovalo přímo před domem.",
            "Slunce pomalu zapadalo za horizont.",
            "Děti hrály fotbal na zahradě.",
            "Pes štěkal na poštovního doručovatele.",
            "Všechno špatné je pro něco dobré.",
            "V kavárně hrála příjemná hudba.",
            "Stůl byl plný knih a časopisů.",
            "Zmrzlina rychle roztála ve slunci.",
            "Ztratil klíče a nemohl se dostat dovnitř.",
            "Telefon zvonil, ale nikdo neodpovídal.",
            "V parku bylo plno lidí.",
            "Pohled z okna byl dechberoucí.",
            "Kniha ležela otevřená na stole.",
            "Autobus přijel přesně na čas.",
            "Džus byl osvěžující a sladký.",
            "Větrník se točil na střeše.",
            "Učitel vysvětloval složitý problém.",
            "Svítilna na stole přestala fungovat.",
            "Děti sbíraly kamínky na pláži.",
            "Všechny květiny ve váze uvadly.",
            "Pes si hrál se svou hračkou.",
            "Obloha byla čistě modrá.",
            "Četl si noviny při snídani.",
            "Telefonní hovor byl krátký a stručný.",
            "Vajíčka na snídani byla akorát.",
            "Na stěně visel nový obraz.",
            "Psala dlouhý dopis svému příteli.",
            "Večer jsme šli na koncert.",
            "Auto bylo po nehodě poničené.",
            "Ráno bylo chladno a mlhavo.",
            "Květináč na parapetu spadl.",
            "Všichni tleskali na konci představení.",
            "Zmrzlina byla příliš tvrdá na to, aby se dala lžící nabrat.",
            "Veverka skákala z větve na větev.",
            "Káva byla silnější, než obvykle.",
            "Pták zpíval na střeše.",
            "Šálek na čaj se rozbil o zem.",
            "Ulice byla po bouřce plná větví.",
            "Věci byly rozhozené po celém pokoji.",
            "Kniha spadla ze stolu.",
            "Větrák se otáčel pomalu.",
            "Děti kreslily křídou na chodníku.",
            "Stůl byl pokrytý papíry.",
            "Večerní film byl zábavný.",
            "Otevřel okno, aby větral.",
            "Sousedé měli hlasitou párty.",
            "Pes spal v koutě pokoje.",
            "Oblaky se hromadily nad městem.",
            "Listí šustilo pod nohama.",
            "Zavřel knihu a postavil ji na polici.",
            "V noci bylo slyšet hřmění.",
            "Auto bylo umyté a čisté.",
            "Ráno se probudil a vyhlédl z okna.",
            "Kočka seděla na střeše a dívala se dolů.",
            "Ulice byly po dešti kluzké.",
            "Auto zaparkovalo přímo před domem.",
            "Slunce pomalu zapadalo za horizont.",
            "Děti hrály fotbal na zahradě.",
            "Pes štěkal na poštovního doručovatele.",
            "Všechno špatné je pro něco dobré.",
            "V kavárně hrála příjemná hudba.",
            "Stůl byl plný knih a časopisů.",
            "Zmrzlina rychle roztála ve slunci.",
            "Ztratil klíče a nemohl se dostat dovnitř.",
            "Telefon zvonil, ale nikdo neodpovídal.",
            "V parku bylo plno lidí.",
            "Pohled z okna byl dechberoucí.",
            "Kniha ležela otevřená na stole.",
            "Autobus přijel přesně na čas.",
            "Džus byl osvěžující a sladký.",
            "Větrník se točil na střeše.",
            "Učitel vysvětloval složitý problém.",
            "Svítilna na stole přestala fungovat.",
            "Děti sbíraly kamínky na pláži.",
            "Všechny květiny ve váze uvadly.",
            "Pes si hrál se svou hračkou.",
            "Obloha byla čistě modrá.",
            "Četl si noviny při snídani.",
            "Telefonní hovor byl krátký a stručný.",
            "Vajíčka na snídani byla akorát.",
            "Na stěně visel nový obraz.",
            "Psala dlouhý dopis svému příteli.",
            "Večer jsme šli na koncert.",
            "Auto bylo po nehodě poničené.",
            "Ráno bylo chladno a mlhavo.",
            "Květináč na parapetu spadl.",
            "Všichni tleskali na konci představení.",
            "Zmrzlina byla příliš tvrdá na to, aby se dala lžící nabrat.",
            "Veverka skákala z větve na větev.",
            "Káva byla silnější, než obvykle.",
            "Pták zpíval na střeše.",
            "Šálek na čaj se rozbil o zem.",
            "Ulice byla po bouřce plná větví.",
            "Věci byly rozhozené po celém pokoji.",
            "Kniha spadla ze stolu.",
            "Větrák se otáčel pomalu.",
            "Děti kreslily křídou na chodníku.",
            "Stůl byl pokrytý papíry.",
            "Večerní film byl zábavný.",
            "Otevřel okno, aby větral.",
            "Sousedé měli hlasitou párty.",
            "Pes spal v koutě pokoje.",
            "Oblaky se hromadily nad městem.",
            "Listí šustilo pod nohama.",
            "Zavřel knihu a postavil ji na polici.",
            "V noci bylo slyšet hřmění.",
            "Auto bylo umyté a čisté.",
            "Ráno se probudil a vyhlédl z okna.",
            "Kočka seděla na střeše a dívala se dolů.",
            "Ulice byly po dešti kluzké.",
            "Auto zaparkovalo přímo před domem.",
            "Slunce pomalu zapadalo za horizont.",
            "Děti hrály fotbal na zahradě.",
            "Pes štěkal na poštovního doručovatele.",
            "Všechno špatné je pro něco dobré.",
            "V kavárně hrála příjemná hudba.",
            "Stůl byl plný knih a časopisů.",
            "Zmrzlina rychle roztála ve slunci.",
            "Ztratil klíče a nemohl se dostat dovnitř.",
            "Telefon zvonil, ale nikdo neodpovídal.",
            "V parku bylo plno lidí.",
            "Pohled z okna byl dechberoucí.",
            "Kniha ležela otevřená na stole.",
            "Autobus přijel přesně na čas.",
            "Džus byl osvěžující a sladký.",
            "Větrník se točil na střeše.",
            "Učitel vysvětloval složitý problém.",
            "Svítilna na stole přestala fungovat.",
            "Děti sbíraly kamínky na pláži.",
            "Všechny květiny ve váze uvadly.",
            "Pes si hrál se svou hračkou.",
            "Obloha byla čistě modrá.",
            "Četl si noviny při snídani.",
            "Telefonní hovor byl krátký a stručný.",
            "Vajíčka na snídani byla akorát.",
            "Na stěně visel nový obraz.",
            "Psala dlouhý dopis svému příteli.",
            "Večer jsme šli na koncert.",
            "Auto bylo po nehodě poničené.",
            "Ráno bylo chladno a mlhavo.",
            "Květináč na parapetu spadl.",
            "Všichni tleskali na konci představení.",
            "Zmrzlina byla příliš tvrdá na to, aby se dala lžící nabrat.",
            "Veverka skákala z větve na větev.",
            "Káva byla silnější, než obvykle.",
            "Pták zpíval na střeše.",
            "Šálek na čaj se rozbil o zem.",
            "Ulice byla po bouřce plná větví.",
            "Věci byly rozhozené po celém pokoji.",
            "Kniha spadla ze stolu.",
            "Větrák se otáčel pomalu.",
            "Děti kreslily křídou na chodníku.",
            "Stůl byl pokrytý papíry.",
            "Večerní film byl zábavný.",
            "Otevřel okno, aby větral.",
            "Sousedé měli hlasitou párty.",
            "Pes spal v koutě pokoje.",
            "Oblaky se hromadily nad městem.",
            "Listí šustilo pod nohama.",
            "Zmrzlina rychle roztála ve slunci.",
            "Ztratil klíče a nemohl se dostat dovnitř.",
            "Telefon zvonil, ale nikdo neodpovídal.",
            "V parku bylo plno lidí.",
            "Pohled z okna byl dechberoucí.",
            "Kniha ležela otevřená na stole.",
            "Autobus přijel přesně na čas.",
            "Džus byl osvěžující a sladký.",
            "Větrník se točil na střeše.",
            "Učitel vysvětloval složitý problém.",
            "Svítilna na stole přestala fungovat.",
            "Děti sbíraly kamínky na pláži.",
            "Všechny květiny ve váze uvadly.",
            "Pes si hrál se svou hračkou.",
            "Obloha byla čistě modrá.",
            "Na stěně visel nový obraz.",
            "Psala dlouhý dopis svému příteli.",
            "Večer jsme šli na koncert.",
            "Auto bylo po nehodě poničené.",
            "Ráno bylo chladno a mlhavo.",
            "Květináč na parapetu spadl.",
            "Všichni tleskali na konci představení.",
            "Zmrzlina byla příliš tvrdá na to, aby se dala lžící nabrat.",
            "Sousedé měli hlasitou párty.",
            "Pes spal v koutě pokoje.",
            "Oblaky se hromadily nad městem.",
            "Listí šustilo pod nohama.",
            "Zavřel knihu a postavil ji na polici.",
            "V noci bylo slyšet hřmění.",
            "Auto bylo umyté a čisté.",
            "Květiny byly čerstvě zalité.",
            "Kniha byla pohodlně uložená v regálu.",
            "Psa svrbělo ucho.",
            "Měsíc svítil jasně na noční obloze.",
            "Děti sbíraly mušle na pláži.",
            "Telefon ticho ležel na stole.",
            "Vůně kávy se line kuchyní.",
            "Stromy se lehce hýbaly ve větru.",
            "Pták přistál na okenním parapetu.",
            "Zvonky na dveřích zazvonily.",
            "Auto pomalu projíždělo ulicí.",
            "List papíru byl hladký a bílý.",
            "Hodiny tikaly klidně na stěně.",
            "Skořápka ořechu ležela na zemi.",
            "Záclony byly lehce roztažené.",
            "Pes spokojeně spal na podlaze.",
            "Večer jsme pozorovali hvězdy.",
            "Kočka pronásledovala svůj stín.",
            "Dětský smích zněl ze zahrady.",
            "Svítilna na stěně slabě svítila.",
            "Větrák se zastavil a znovu se rozeběhl.",
            "Strom vrhal dlouhý stín.",
            "Vůně čerstvého pečiva se šířila vzduchem.",
            "Psí miska byla plná granulí.",
            "Kočka ležela skládaná na židli.",
            "Ulice byla mokrá po dešti.",
            "V koupelně kapala voda z kohoutku.",
            "Obloha byla plná letících ptáků.",
        ]

    def get_random_sentence(self):
        self.sentences.append(my_list)
        return random.choice(self.sentences)

